// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvcnymlvoouryxuriqtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Y255bWx2b291cnl4dXJpcXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODU0ODQsImV4cCI6MjA2ODI2MTQ4NH0.GEqlRCi9Ejj4ew5OEwCu9yAY1I-mw_OL1HBe2CtCH4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});